# vi: set ft=ruby :
VM_ID = "kube"
NUM_WORKER_NODES = 2

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = true

# Single Control-Plane node
  config.vm.define "#{VM_ID}-master" do |node|
    node.vm.provider "virtualbox" do |vb|
      vb.name = "#{VM_ID}-master"
      vb.memory = 3192
      vb.cpus = 2
    end
    node.vm.hostname = "#{VM_ID}-master"
    node.vm.network :public_network, protocol: "tcp", bridge: "enp1s0", ip: "192.168.0.215"
  end

# Worker nodes
  (1..NUM_WORKER_NODES).each do |i|
    config.vm.define "#{VM_ID}-worker-#{i}" do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.name = "#{VM_ID}-worker-#{i}"
        vb.memory = 3096
        vb.cpus = 2
      end
      node.vm.hostname = "#{VM_ID}-worker-#{i}"
      node.vm.network :public_network, protocol: "tcp", bridge: "enp1s0"
	  node.vm.provision "shell", inline: <<-SHELL
		hostname -I | cut -d' ' -f2 > ip.txt
		ip=`cat ip.txt`
		a=`sudo cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf | grep 192.168. |  cut -d' ' -f2 | cut -d'=' -f2 | sed 's/.$//'`
		sudo sed -i 's/'$a'/'$ip'/g' /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
		sudo systemctl daemon-reload
		sudo systemctl restart kubelet
		SHELL
    end
  end
end
